#!/bin/bash
set -eo pipefail
IFS=$'\n\t'

brew tap caskroom/cask
brew tap wooga/unityversions

if [ "$(which aws)" == "" ]; then brew install awscli; fi

if [ ! -f /Applications/Unity/Unity.app/Contents/Pkginfo ]; then
  brew cask install unity@2017.1.0f3
fi

# Android only requirements
if [[ $RAKE_BUILD_TASKS = *"android"* ]]; then
  # Android SDK
  if [ "$(which android)" == "" ]; then
    brew cask install android-sdk
  fi

  # Android NDK
  if [ $USE_IL2CPP_ON_ANDROID == "true" ] && [ "$(which ndk-build)" == "" ]; then
    brew tap gocarrot/homebrew-ndkversions
    brew cask install android-ndk@10e
  fi

  # Android SDK components
  echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-26"
  echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;26.0.2"

  # Unity Android support
  if [ ! -f /Applications/Unity/PlaybackEngines/AndroidPlayer/ivy.xml ]; then
    brew cask install unity-android-support-for-editor@2017.1.0f3
  fi
fi

# Unity iOS Support
if [[ $RAKE_BUILD_TASKS = *"ios"* ]]; then
  if [ ! -f /Applications/Unity/PlaybackEngines/WebGLSupport/ivy.xml ]; then
    brew cask install unity-ios-support-for-editor@2017.1.0f3
  fi
fi

# Unity WebGL Support
if [[ $RAKE_BUILD_TASKS = *"webgl"* ]]; then
  if [ ! -f /Applications/Unity/PlaybackEngines/iOSSupport/ivy.xml ]; then
    brew cask install unity-webgl-support-for-editor@2017.1.0f3
  fi
fi
