version: 2
jobs:
  build:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      UNITY_HOME: /Applications/Unity-2017.1.0f3/
      ANDROID_HOME: /usr/local/share/android-sdk
      ANDROID_NDK_HOME: /usr/local/share/android-ndk
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Tasks To Build...
          command: echo $RAKE_BUILD_TASKS
      - restore_cache:
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.RAKE_BUILD_TASKS }}
      - run:
          name: Fix 'Homebrew must be run under Ruby 2.3!'
          command: brew update
      - run:
          name: Homebrew Depenendcies
          command: ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew/
            - vendor/bundle
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.RAKE_BUILD_TASKS }}
      - add_ssh_keys:
          fingerprints:
            - "ab:48:b1:f2:a7:e9:0f:ba:81:3b:0c:16:48:6b:91:3d"
      - run:
          name: Download, Import and Configure Teak SDK for Unity
          command: bundle exec rake package:download package:import config:all
      - run:
          name: Acquire Unity License
          command: bundle exec rake unity_license:acquire
      - run:
          name: Build Teak Cleanroom
          command: bundle exec rake $RAKE_BUILD_TASKS
          no_output_timeout: 50m
      - run:
          command: |
            mkdir -p /tmp/unity_logs
            cp *.unity.log /tmp/unity_logs
            bundle exec rake unity_license:release
          when: on_fail
      - store_artifacts:
          path: /tmp/unity_logs
      - persist_to_workspace:
          root: .
          paths:
            - teak-unity-cleanroom.ipa
            - teak-unity-cleanroom.apk
            - teak-unity-cleanroom.zip
            - TEAK_VERSION
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Tasks To Deploy...
          command: echo $RAKE_DEPLOY_TASKS
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Upload Cleanroom Apps to S3
          command: bundle exec rake $RAKE_DEPLOY_TASKS
workflows:
  version: 2
  all:
    jobs:
      - build:
          context: unity-cleanroom
      - deploy:
          context: unity-cleanroom
          requires:
            - build
          filters:
            branches:
              only: [master, /hotfix.*/]
  # android:
  #   jobs:
  #     - build:
  #         context: android-cleanroom
  #     - deploy:
  #         context: android-cleanroom
  #         requires:
  #           - build
  #         filters:
  #           branches:
  #             only: [master, /hotfix.*/]
  # ios:
  #   jobs:
  #     - build:
  #         context: ios-cleanroom
  #     - deploy:
  #         context: ios-cleanroom
  #         requires:
  #           - build
  #         filters:
  #           branches:
  #             only: [master, /hotfix.*/]
  # webgl:
  #   jobs:
  #     - build:
  #         context: webgl-cleanroom
  #     - deploy:
  #         context: webgl-cleanroom
  #         requires:
  #           - build
  #         filters:
  #           branches:
  #             only: [master, /hotfix.*/]
