version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      ANDROID_HOME: /usr/local/share/android-sdk
      ANDROID_NDK_HOME: /usr/local/share/android-ndk
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Tasks To Build...
          command: echo $RAKE_BUILD_TASKS
      - restore_cache:
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.RAKE_BUILD_TASKS }}-{{ .Environment.HOMEBREW_VERSION }}-{{ .Environment.UNITY_VERSION }}
      - run:
          name: Check Homebrew Version
          command: |
            [ `brew --version | sed -n 1p | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'` = $HOMEBREW_VERSION ] || brew update
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          name: Ruby Gems
          command: |
            gem update bundler
            bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - /usr/local/share/android-sdk
            - /usr/local/Homebrew
            - ~/Library/Caches/Homebrew
            - vendor/bundle
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.RAKE_BUILD_TASKS }}-{{ .Environment.HOMEBREW_VERSION }}-{{ .Environment.UNITY_VERSION }}
      - add_ssh_keys:
          fingerprints:
            - "ab:48:b1:f2:a7:e9:0f:ba:81:3b:0c:16:48:6b:91:3d"
      - run:
          name: Build Teak Cleanroom
          command: |
            export FL_TEAK_SDK_VERSION=`git ls-remote --tags "git://github.com/GoCarrot/teak-unity.git" | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -n 1`
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake unity_license:acquire package:download package:import config:all $RAKE_BUILD_TASKS
          no_output_timeout: 60m
      - run:
          command: |
            mkdir -p /tmp/unity_logs
            cp unity.*.log /tmp/unity_logs
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake unity_license:release
          when: on_fail
      - store_artifacts:
          path: /tmp/unity_logs
workflows:
  version: 2
  all:
    jobs:
      - build:
          name: Unity-5
          context: unity-5
      - build:
          name: Unity-2017
          context: unity-2017
          requires:
            - Unity-5
      - build:
          name: Unity-2018
          context: unity-2018
          requires:
            - Unity-2017

