version: 2.1
jobs:
  build:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      ANDROID_HOME: /usr/local/share/android-sdk
      ANDROID_NDK_HOME: /usr/local/share/android-ndk
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          shell: /bin/bash -eo pipefail
          name: Set Ruby Version 2.3
          command: echo "ruby-2.3" > .ruby-version
      - run:
          name: Tasks To Build...
          command: echo $RAKE_BUILD_TASKS
      - restore_cache:
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.RAKE_BUILD_TASKS }}-{{ .Environment.HOMEBREW_VERSION }}-{{ .Environment.UNITY_VERSION }}
      - run:
          name: Check Homebrew Version
          command: |
            [ `brew --version | sed -n 1p | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'` = $HOMEBREW_VERSION ] || brew update
      - run:
          name: Homebrew Depenendcies
          command: HOMEBREW_NO_AUTO_UPDATE=1 ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - /usr/local/Homebrew/
            - ~/Library/Caches/Homebrew
            - vendor/bundle
          key: v1-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}-{{ .Environment.RAKE_BUILD_TASKS }}-{{ .Environment.HOMEBREW_VERSION }}-{{ .Environment.UNITY_VERSION }}
      - add_ssh_keys:
          fingerprints:
            - "ab:48:b1:f2:a7:e9:0f:ba:81:3b:0c:16:48:6b:91:3d"
      - run:
          name: Download, Import and Configure Teak SDK for Unity
          command: |
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake package:download package:import config:all
      - run:
          name: Acquire Unity License
          command: |
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake unity_license:acquire
      - run:
          name: Build Teak Cleanroom
          command: |
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake $RAKE_BUILD_TASKS
            mkdir $UNITY_VERSION
            mv teak-unity-cleanroom.* $UNITY_VERSION/
          no_output_timeout: 50m
      - run:
          command: |
            mkdir -p /tmp/unity_logs
            cp *.unity.log /tmp/unity_logs
            export UNITY_HOME=/Applications/Unity-$UNITY_VERSION/
            bundle exec rake unity_license:release
          when: on_fail
      - store_artifacts:
          path: /tmp/unity_logs
      - persist_to_workspace:
          root: .
          paths:
            - $UNITY_VERSION/teak-unity-cleanroom.ipa
            - $UNITY_VERSION/teak-unity-cleanroom.apk
            - $UNITY_VERSION/teak-unity-cleanroom.zip
            - TEAK_VERSION
workflows:
  version: 2
  all:
    jobs:
      - build:
          name: Unity-5
          context: unity-5
      - build:
          name: Unity-2017
          context: unity-2017
      - build:
          name: Unity-2018
          context: unity-2018

