# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
FASTFILE_PATH = File.expand_path(File.dirname(File.dirname(__FILE__)))
XCODE_PROJECT = File.join(FASTFILE_PATH, "..", "Unity-iPhone", "Unity-iPhone.xcodeproj")
CONFIG_TYPE = "development"
TEAM_ID = "7FLZTACJ82"
TEAK_APP_EXTENSIONS = ["TeakNotificationService", "TeakNotificationContent"]
BUILD_CONFIGURATIONS = ["Debug", "Release", "ReleaseForRunning", "ReleaseForProfiling"]

default_platform(:ios)

before_all do
  setup_circle_ci
end

desc "Copy or download the Teak SDK"
lane :sdk do
  version = teak_sdk(
    sdk: :unity,
    destination: '.'
  )
  File.write(File.join("..", "TEAK_VERSION"), version)
end

platform :ios do
  desc "Build targeting Dev profile"
  lane :dev do
    BUILD_CONFIGURATION = "Debug"

    # Create/fetch and store provisioning profiles
    ios_provisioning_profile = {}
    ["io.teak.app.unity.dev"].each do |app_id|
      match(
        app_identifier: app_id,
        type: CONFIG_TYPE,
        read_only:true
      )
      provisioning_profile_env = Match::Utils.environment_variable_name_profile_path(
        app_identifier: app_id,
        type: CONFIG_TYPE
      )
      ios_provisioning_profile["Unity-iPhone"] = ENV[provisioning_profile_env]

      TEAK_APP_EXTENSIONS.each do |app_extension_name|
        match(
          app_identifier: "#{app_id}.#{app_extension_name}",
          type: CONFIG_TYPE,
          read_only:true
        )

        provisioning_profile_env = Match::Utils.environment_variable_name_profile_path(
          app_identifier: "#{app_id}.#{app_extension_name}",
          type: CONFIG_TYPE
        )
        ios_provisioning_profile[app_extension_name] = ENV[provisioning_profile_env]
      end
    end

    # Add Teak app extensions
    teak_extensions(
      xcodeproj:XCODE_PROJECT,
      #source:"~/Code/teak-ios"
    )

    TEAK_APP_EXTENSIONS.concat(["Unity-iPhone"]).each do |target|
      update_project_provisioning(
        xcodeproj: XCODE_PROJECT,
        target_filter: target,
        profile: ios_provisioning_profile[target],
        build_configuration: BUILD_CONFIGURATION
      )
    end

    sync_code_signing
    disable_automatic_code_signing(path: XCODE_PROJECT)

    build_ios_app(
      project: XCODE_PROJECT,
      scheme: "Unity-iPhone",
      configuration: BUILD_CONFIGURATION,
      clean: true,
      output_directory: File.join(FASTFILE_PATH, ".."),
      output_name: "teak-unity-cleanroom.ipa",
      export_method: CONFIG_TYPE
    )

    enable_automatic_code_signing(path: XCODE_PROJECT)
  end
end
