# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
FASTFILE_PATH = File.expand_path(File.dirname(File.dirname(__FILE__)))
XCODE_PROJECT = File.join(FASTFILE_PATH, "..", "Unity-iPhone", "Unity-iPhone.xcodeproj")
CONFIG_TYPE = "development"
TEAM_ID = "7FLZTACJ82"
TEAK_APP_EXTENSIONS = ["TeakNotificationService", "TeakNotificationContent"]
BUILD_CONFIGURATIONS = ["Debug", "Release", "ReleaseForRunning", "ReleaseForProfiling"]
CIRCLE_ARTIFACTS = ENV.fetch('CIRCLE_ARTIFACTS', nil)

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci if !CIRCLE_ARTIFACTS.nil?
  end

  desc "Setup"
  lane :setup do
    ["io.teak.app.unity.dev", "io.teak.app.unity.prod"].each do |app_id|
      produce(
        app_identifier: app_id,
        app_name: "Teak Unity Cleanroom",
        skip_itc: true,
        enable_services: {
          push_notification: "on",
          associated_domains: "on"
        }
      )
      match(
        app_identifier: app_id,
        type: CONFIG_TYPE,
        force: true
      )

      TEAK_APP_EXTENSIONS.each do |app_extension_name|
        produce(
          app_identifier: "#{app_id}.#{app_extension_name}",
          app_name: app_extension_name,
          skip_itc: true
        )
        match(
          app_identifier: "#{app_id}.#{app_extension_name}",
          type: CONFIG_TYPE,
          force: true
        )
      end
    end
  end

  desc "Test things"
  lane :test do
    teak_extensions(
      xcodeproj:XCODE_PROJECT,
      #source:"~/Code/teak-ios"
    )
  end

  desc "Build targeting Dev profile"
  lane :dev do
    # Create/fetch and store provisioning profiles
    ios_provisioning_profile = {}
    ["io.teak.app.unity.dev"].each do |app_id|
      match(
        app_identifier: app_id,
        type: CONFIG_TYPE,
        force: true
      )
      provisioning_profile_env = Match::Utils.environment_variable_name_profile_path(
        app_identifier: app_id,
        type: CONFIG_TYPE
      )
      ios_provisioning_profile["Unity-iPhone"] = ENV[provisioning_profile_env]

      TEAK_APP_EXTENSIONS.each do |app_extension_name|
        match(
          app_identifier: "#{app_id}.#{app_extension_name}",
          type: CONFIG_TYPE,
          force: true
        )

        provisioning_profile_env = Match::Utils.environment_variable_name_profile_path(
          app_identifier: "#{app_id}.#{app_extension_name}",
          type: CONFIG_TYPE
        )
        ios_provisioning_profile[app_extension_name] = ENV[provisioning_profile_env]
      end
    end

    # Update entitlements
    update_entitlements(
      push_enabled: true,
      push_ios: true,
      push_development: true,
      entitlements_project_path: XCODE_PROJECT
    )

    # Add Teak app extensions
    teak_extensions(
      xcodeproj:XCODE_PROJECT,
      #source:"~/Code/teak-ios"
    )

    disable_automatic_code_signing(
      path: XCODE_PROJECT
    )

    puts (Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING] || {}).inspect

    TEAK_APP_EXTENSIONS.concat(["Unity-iPhone"]).each do |target|
      BUILD_CONFIGURATIONS.each do |configuration|
        update_project_provisioning(
          xcodeproj: XCODE_PROJECT,
          target_filter: target,
          profile: ios_provisioning_profile[target],
          build_configuration: configuration
        )
      end
    end

    build_ios_app(
      project: XCODE_PROJECT,
      xcargs: '-allowProvisioningUpdates',
      scheme: "Unity-iPhone",
      clean: true,
      output_directory: File.join(FASTFILE_PATH, ".."),
      output_name: "teak-unity-cleanroom.ipa",
      export_method: CONFIG_TYPE
    )
  end
end
